# Entity Update frequency in Milliseconds.
entityUpdateSpeed: 100

# At what range in blocks the Skeletons will use a sword.
skeletonSwordSwitch: # Skeletons will use a wooden sword.
  enabled: true
  swordRange: 5

# At what range in blocks the Wither Skeletons will use a sword.
witherSkeletonSwordSwitch: # Wither Skeletons will use a bow with the flame enchantment.
  enabled: true
  swordRange: 8

# Makes it possible for (Wither) Skeletons to mount (Cave) Spiders.
skeletonSpiderMount:
  enabled: true
  updateEntityfromPlayer: 16 # How many blocks from the player the updating starts. 
  mountFindRange: 4 # Amount of blocks that (Wither) Skeletons will search for a (Cave) Spider to mount.

# Makes it possible for Baby Zombies to mount Chickens.
zombieChickenMount:
  enabled: true
  updateEntityfromPlayer: 16 # How many blocks from the player the updating starts. 
  mountFindRange: 4 # Amount of blocks that Baby Zombies will search for a Chicken to mount.

# Makes it possible for Charged Creepers to spawn more regularly.
chargedCreeperSpawn:
  enabled: true
  spawnChance: 50 # 1 in 50 Creepers will be a Charged Creeper.
  
# Makes Creepers spawn more regularly with effects.
creeperSpawnPotionEffect:
  enabled: true
  effectDuration: 60 # Duration of the given effect.
  spawnChance: 20 # 1 in 20 Creepers spawns with an effect.
  positiveEffects: true
  # Includes: ABSORPTION, RESISTANCE, INVISIBILITY, JUMP BOOST, WATER BREATHING, REGENERATION, SPEED, STRENGTH, FIRE RESISTANCE, HASTE
  negativeEffects: true
  # Includes: POISON, WITHER, BLINDNESS, MINING FATIQUE, WEAKNESS, HUNGER, NAUSEA
  rareEffects: true
  # Includes: LEVITATION, DOLPHINS GRACE, GLOWING, LUCK, BAD OMEN, SATURATION, CONDUIT POWER

# Whether Witches can spawn Baby Zombies at night to help it fight the player.
witchNecromancer: # Summoned Baby Zombies won't drop Anything.
  enabled: true
  cooldown: 30 # How many Seconds to wait before summoning again.
  spawnAmount: 3 # The maximum amount of Zombies that will spawn at each interval. (note: Spawn amounts will differ due to RNG).
  spawnRadius: 3 # How many blocks away from the Witch the Baby Zombies can spawn.
  scanRadius: 16 # The distance from the player that will be checked for Witches.

# Wether the Wither can spawn Wither Skeletons to help him in battle.
witherReinforcements: # Summoned Wither Skeletons won't drop Anything
  enabled: true
  cooldown: 45 # How many Seconds to wait before summoning again.
  spawnRadius: 10 # Maximum amount of blocks that Wither Skeletons can spawn from the Wither.
  spawnChance: 10 # 1/100 Procental Chance that reinforcements will spawn if the Wither is attacked.
  spawnAmount: 2 # Maximum amount of Wither Skeletons that will spawn at each interval. (note: Spawn amounts will differ due to RNG).

# Wether the Wither can give negative effects to players around it.
witherEffects: # Includes: BLINDNESS, NAUSEA, HUNGER, MINING FATIQUE, WEAKNESS
  enabled: true
  cooldown: 40 # How many Seconds to wait before releasing effects again.
  spawnChance: 10 # The chance the effects will happen if the Wither is attacked.
  attackRadius: 8 # Maximum radius of the attack.
  attackDuration: 10 # Duration of the given potion effect.

# Wether the Ender Dragon will rest on The End Portal.
NoDragonPerching:
  enabled: true

# Wether The Ender Dragon spawns Baby Ender Dragons to kill the player.
babyEnderDragons:
  enabled: true
  spawnRadius: 15 # Maximum amount of blocks that Baby Ender Dragons can spawn from The Ender Dragon.
  spawnChance: 10 # 1/100 Procental Chance that the Baby Ender Dragon spawn will occur.
  spawnAmount: 2 # Maximum amount of Baby Ender Dragons that will spawn at each interval. (note: Spawn amounts will differ due to RNG).
  damageBooster: 2 # Amount of damage that the Baby Ender Dragons will do.
  dragonRegen: true # Whether The Ender Dragon will regenerate health if a Baby Ender Dragon hits a player.

# Wether The Ender Dragon spawns Endermites to kill the player.
enderDragonMites:
  enabled: true
  spawnRadius: 15 # Max distance from the dragon where the babies could spawn.
  spawnChance: 10 # 1/100 Procental Chance that the Endermite spawn will occur.
  spawnAmount: 2 # Maximum amount of Endermite that will spawn at each interval. (note: Spawn amounts will differ due to RNG).
  damageBooster: 2 # Amount of damage that the Endermite will do.
  dragonRegen: true # Whether The Ender Dragon will regenerate health if an Endermite hits a player.

